---
- name: Set up cluster-wide configuration.
  hosts: cluster
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks: []

- name: Configure storage node (node 3).
  hosts: storage
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Set up storage.
      include_tasks: tasks/storage.yml
      when: storage_configure

- name: Configure the control plane (node 1).
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks: []

- name: Configure the nodes (nodes 2-4).
  hosts: nodes
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks: []
