---
- name: Set up networking configuration.
  hosts: cluster
  gather_facts: false
  become: true

  handlers:
    - name: restart dhcpcd
      service:
        name: dhcpcd
        state: restarted

  vars_files:
    - config.yml

  tasks:
    - name: Configure static IP address on each node.
      ansible.builtin.blockinfile:
        path: /etc/dhcpcd.conf
        marker: "# ANSIBLE MANAGED - static ip {mark}"
        block: |
          interface eth0
          static ip_address={{ ipv4_subnet_prefix }}.{{ ip_host_octet }}/24
          static routers={{ ipv4_subnet_prefix }}.1
          static domain_name_servers={{ ipv4_subnet_prefix }}.1
      notify: restart dhcpcd

    # TODO
    - name: Configure hosts file so nodes can see each other by hostname.
      meta: noop

    - name: Set active Internet gateway interface on node 1.
      ansible.builtin.blockinfile:
        path: /etc/dhcpcd.conf
        marker: "# ANSIBLE MANAGED - Internet routing metric {mark}"
        block: |
          interface {{ active_internet_interface }}
          metric 100
      delegate_to: "{{ groups['control_plane'][0] }}"
      run_once: true
      notify: restart dhcpcd


- name: Configure node 1 as a router.
  hosts: control_plane
  gather_facts: false
  become: true

  handlers:
    - name: restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted

    - name: persist iptables rules
      ansible.builtin.command: netfilter-persistent save

  vars_files:
    - config.yml

  tasks:
    - name: Install routing prerequisites.
      ansible.builtin.apt:
        name:
          - dnsmasq
          - netfilter-persistent
          - iptables-persistent
        state: present

    - name: Ensure netfilter-persistent is enabled.
      ansible.builtin.service:
        name: netfilter-persistent
        enabled: true

    - name: Ensure dnsmasq is running and enabled.
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true

    - name: "Configure iptables for {{ active_internet_interface }} masquerade."
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ active_internet_interface }}"
        jump: MASQUERADE
      notify: persist iptables rules

    - name: Enable IPv4 forwarding.
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: Configure dnsmasq for bridged DNS.
      ansible.builtin.copy:
        dest: /etc/dnsmasq.d/bridge.conf
        content: |
          interface=eth0
          bind-interfaces
          server=1.1.1.1
          server=1.0.0.1
          domain-needed
          bogus-priv
      notify: restart dnsmasq

    # See: https://github.com/geerlingguy/turing-pi-2-cluster/issues/9
    - name: Add crontab task to restart dnsmasq.
      ansible.builtin.cron:
        name: "restart dnsmasq if not running"
        minute: "*"
        job: "/usr/bin/systemctl status dnsmasq || /usr/bin/systemctl restart dnsmasq"
