---
- name: Set up networking configuration.
  hosts: cluster
  gather_facts: false
  become: true

  handlers:
    - name: restart dhcpcd
      service:
        name: dhcpcd
        state: restarted

  vars_files:
    - config.yml

  tasks:
    - name: Configure static IP address on each node.
      ansible.builtin.blockinfile:
        path: /etc/dhcpcd.conf
        marker: "# ANSIBLE MANAGED - static ip {mark}"
        block: |
          interface eth0
          static ip_address={{ ipv4_subnet_prefix }}.{{ ip_host_octet }}/24
          static routers={{ ipv4_subnet_prefix }}.1
          static domain_name_servers=1.1.1.1,8.8.8.8
      notify: restart dhcpcd

    - name: Set active Internet gateway interface on node 1.
      ansible.builtin.blockinfile:
        path: /etc/dhcpcd.conf
        marker: "# ANSIBLE MANAGED - Internet routing metric {mark}"
        block: |
          interface {{ active_internet_interface }}
          metric 100
      delegate_to: "{{ groups['control_plane'][0] }}"
      run_once: true
      notify: restart dhcpcd
